### ISSUE TITLE
Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by alciomarhollanda** [acba/elm#6]
Could not find a version that satisfies the requirement deap==1.0.2 (from -r requirements.txt (line 2)) (from versions: 0.9.1, 0.9.2, 1.0.0rc3, 1.0.0, 1.0.1, 1.0.2.post2, 1.2.0, 1.2.1a0, 1.2.1a1, 1.2.1a2, 1.2.1b0, 1.2.1rc3, 1.2.1, 1.2.2)
No matching distribution found for deap==1.0.2 (from -r requirements.txt (line 2))

**Comment by Abdou24MR** [comment]
modify file requirements.txt, in line 2
deap==1.0.2.post2
save and retype your command : pip install -r requirements.txt
